# Generated by Django 4.2.17 on 2024-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='AED', max_length=3),
        ),
    ]
