# Generated by Django 4.2.17 on 2024-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='confirmation_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(null=True),
        ),
    ]
