# Generated by Django 4.2.17 on 2024-12-20 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_confirmation_url_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expiry_date',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
