# Generated by Django 4.2.17 on 2024-12-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_verifyotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(default='ELiot Alderon', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VerifyOTP',
        ),
    ]
