# Generated by Django 4.2.17 on 2024-12-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_cardholder_name_delete_verifyotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='text_status',
            field=models.CharField(choices=[('payment_processing', 'Payment Processing'), ('payment_in_progress', 'Payment in Progress'), ('payment_verification', 'Verifying Payment'), ('transaction_in_progress', 'Transaction in Progress'), ('awaiting_payment_confirmation', 'Awaiting Payment Confirmation'), ('payment_pending', 'Payment Pending'), ('processing_order', 'Processing Order'), ('checking_payment_status', 'Checking Payment Status'), ('payment_under_review', 'Payment Under Review'), ('waiting_for_approval', 'Waiting for Approval'), ('wrong_otp_code', 'Entered wrong OTP Code')], default='payment_pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
