# Generated by Django 4.2.17 on 2024-12-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_text_status_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='text_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='errors',
            field=models.CharField(blank=True, choices=[('wrong_otp', 'OTP code has entered incorrectly. Please enter the new one')], default=None, max_length=255, null=True),
        ),
    ]
