# Generated by Django 4.2.17 on 2024-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_text_status_payment_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='issuer',
            field=models.CharField(blank=True, default='Bank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='schema',
            field=models.CharField(blank=True, default='visa', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='errors',
            field=models.CharField(blank=True, choices=[('wrong_otp', 'The OTP code entered is incorrect. Please try again with the correct code.')], default=None, max_length=255, null=True),
        ),
    ]
