# Generated by Django 4.2.17 on 2025-01-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_id_alter_payment_issuer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='issuer',
        ),
        migrations.AlterField(
            model_name='payment',
            name='errors',
            field=models.CharField(blank=True, choices=[('wrong_otp', 'The OTP code entered is incorrect.')], default=None, max_length=255, null=True),
        ),
    ]
