# Generated by Django 4.2.17 on 2025-01-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_payment_issuer_alter_payment_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='schema',
        ),
    ]
